### ISSUE TITLE
error: not found: value assemblyJarName in assembly 

### ISSUE THREAD

**Issue by Nikhil1810** [ZuInnoTe/hadoopcryptoledger#13]
I am new to big data and hadoop, I am trying to make use of hadoopcryptoledger library to do some bitcoin graph analysis, I followed this tutorial Using Spark Scala Graphx to analyze the Bitcoin transaction graph (https://github.com/ZuInnoTe/hadoopcryptoledger/wiki/Using-Spark-Scala-Graphx-to-analyze-the-Bitcoin-transaction-graph)

While executing the command

    sbt clean assembly test it:test 
I ran into an issue:

    /home/jnikhil/hadoopcryptoledger/examples/scala-spark-graphx-    
    bitcointransaction/build.sbt:30: error: not found: value assemblyJarName
    assemblyJarName in assembly := "example-hcl-spark-scala-graphx-bitcointransaction.jar"
    [error] Type error in expression 
    
Does anyone know why am I facing this issue?

**Comment by jornfranke** [comment]
I just cloned the repository and do not see the error that you see.

Did you change in the subfolder /home/jnikhil/hadoopcryptoledger/examples/scala-spark-graphx-    
bitcointransaction ?

Did you modify anything? Are you using an IDE? What sbt version are you using? Please use at least sbt 0.13.5

**Comment by Nikhil1810** [comment]
yeah It was due to the version of sbt that I was using. Thank you so much.
