### ISSUE TITLE
ERROR BitcoinBlockReader:476 - Cannot skip block in InputStream

### ISSUE THREAD

**Issue by jfroscoe** [ZuInnoTe/hadoopcryptoledger#18]
Hi Jorne,

As discussed via email. I was hesitant to raise an issue as I think this may be down to error with me.

Magic, I've tried "F9BEB4D9" and also "F9BEB4D9,FABFB5DA" as well as not setting it.

For maxblocksize I've tried not having set, "2M", "2", "8M", "8". Not sure if the M is supposed to be there.

I'm using the maven module.  Spark 2.10. When using method shown in SparkBitcoinBlockDataSource I get the following error, I think it might actually be a problem with spark setup:

```
java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;
```

I'll try using gradle to build your project and run the examples.

**Comment by jornfranke** [comment]
Hi,
No problem an issue here is also a request for information ;) 
Block size is in byte and the default one is 2 * 1024 * 1024, so neither of your options work.

Which Spark version do you use and which scala version?  It could be that you need to select the module based on Scala 2.11.

**Comment by jfroscoe** [comment]
```
		<dependency>
			<groupId>com.github.zuinnote</groupId>
			<artifactId>spark-hadoopcryptoledger-ds_2.11</artifactId>
			<version>1.0.4</version>
		</dependency>
```

I'm using Spark 2.1.1. Oddly, when I use a local spark instance rather than the cluster, I see a different error:

```
ERROR BitcoinBlockReader:476 - Cannot skip block in InputStream
```

I've changed the max blocksize value to 2097152 but no luck.

I'm working with the first dozen .dat files for now.

**Comment by jornfranke** [comment]
The scala version is important , not the Spark version. Are you using standard bitcoin block data then it should work. Please do try not to set the block size.
Please also check that you only copied the blk*.dat data and not the rev*.dat.

**Comment by jornfranke** [comment]
https://github.com/ZuInnoTe/spark-hadoopcryptoledger-ds/issues/4

**Comment by jornfranke** [comment]
I close this issue, the newest version of the library is 1.0.7 which includes segwit support. if the issue still persists then please create a new one.
