### ISSUE TITLE
Is there a way around the currently supported maximum ethereum block size ?

### ISSUE THREAD

**Issue by skattoju-zz** [ZuInnoTe/hadoopcryptoledger#52]
We are running into exceptions when attempting to do graph analysis using graphframes after creating a dataframe using spark-hadoopcryptoledger-ds. Seems like there are blocksizes bigger than what can fit inside an int ?

java.lang.InterruptedException: org.zuinnote.hadoop.ethereum.format.exception.EthereumBlockReadException: Error: This block size cannot be handled currently (larger then largest number in positive signed int)

**Comment by jornfranke** [comment]
Hmm this seems to be something different. Valid ethereum blocks that I have seen are never larger than 2 GB. Do you have the block number with which it occurs? It looks more like an invalid or incomplete block (or some recent changes to the block structure in Ethereum).

**Comment by jornfranke** [comment]
Do you have more context of the code?

**Comment by jornfranke** [comment]
It could have been due to some changes by somebody else related to the function EthereumUtil.convertIndicatorToRLPSize

**Comment by jornfranke** [comment]
Maybe there is some other file in your folder which is not related to ethereum data ?

**Comment by skattoju-zz** [comment]
That was it there was a rogue file in my folder! Sorry about the false alarm!
