### ISSUE TITLE
Move integration tests from examples into new top-level folder and document in contribution guidelines

### ISSUE THREAD

**Issue by phelps-sg** [ZuInnoTe/hadoopcryptoledger#75]
The integration tests are currently in the `examples/` folder, which makes them hard to find.  Suggest moving into a new top-level folder called `integration-tests/`.  Instructions for running the integration tests could be added to `CONTRIBUTING.md`.

**Comment by jornfranke** [comment]
The examples do not contain integration tests.
Please do not work on any issues before it has been agreed and discussed. Otherwise we cannot accept pull requests.

**Comment by phelps-sg** [comment]
In `examples/spark-bitcoinblock/` folder there is a folder called `integration-test/`.  I was assuming that it was an integration test, but is it merely an example of an integration test?  Can you point me to the correct location for the integration tests?
