### ISSUE TITLE
The comment with the Apache License should be a block comment not a javadoc comment

### ISSUE THREAD

**Issue by phelps-sg** [ZuInnoTe/hadoopcryptoledger#76]
Each source files begins with 

~~~
/**
* Copyright 2017 ZuInnoTe (Jörn Franke) <zuinnote@gmail.com>
*
...
*/
~~~

In the IntelliJ IDE this generates a static warning "Dangling Javadoc comment".

The comment should be a block comment, not a javadoc comment, ie:

~~~
/*
 * Copyright 2017 ZuInnoTe (Jörn Franke) <zuinnote@gmail.com>
 *
...
 */
~~~

**Comment by jornfranke** [comment]
Please do not work on any issues before it has been agreed and discussed. Otherwise we cannot accept pull requests.

**Comment by phelps-sg** [comment]
I am using this library in my own project, which has its own requirements and deadlines, so I may need to work on issues quickly.  I will continue committing to my forked repo.  If you do not want my pull requests that is your prerogative.  I will try not to issue PRs until you have ok-ed the issue, but note that this may result in divergence of the fork.

**Comment by jornfranke** [comment]
Ok, I propose that you finish your project in your repo and then we can see later to integrate it. Maybe then we can simplify the things as well a bit.  I probably will not have the time to review it within your deadlines and I do not want to block you
